export const recentProjects = [
  {
    name: "Libratech",
    description:
      "LibraTech is a modern library management system designed to streamline library operations, improve patron experience, and enhance library engagement.",
    image: "/assets/projects/libratech_desktop.png",
    link: "https://www.facebook.com/100024553238161/videos/947664236424939/",
    date: "June 2023",
    type: "desktop",
    technologies: ["Java", "Firebase", "SMTP"],
  },
  {
    name: "Iskolar ng Bayan",
    description:
      "An application that hosts compiled, comprehensive, and concise reviewers for college entrance examinations. It features groupchats to keep students updated, It has video manuals and readable modules.",
    image: "/assets/projects/iskolar_mobile.png",
    link: "https://dropden.com/facf74488d0b",
    date: "January 2021",
    type: "mobile",
    technologies: ["Android", "Java", "XML", "Python"],
  },
  {
    name: "Iskolar ng Bayan - Web",
    description:
      "An application that hosts compiled, comprehensive, and concise reviewers for college entrance examinations. It features groupchats to keep students updated, It has video manuals and readable modules.",
    image: "/assets/projects/iskolar_web.png",
    link: "https://www.facebook.com/share/v/19HpYW98Wh/",
    date: "May 2024",
    type: "web",
    technologies: ["React", "PHP", "TailwindCSS", "Slim", "DaisyUI"],
  },
  {
    name: "Codiphy",
    description:
      "Codiphy is an AI-powered platform that generates dynamic programming quizzes to sharpen your coding skills effortlessly. Say goodbye to the hassle of quiz creation and embrace an interactive learning experience designed for mastery.",
    image: "/assets/projects/codiphy_web.png",
    link: "https://codiphy.onrender.com",
    date: "Jan 2024",
    type: "web",
    technologies: [
      "ReactJS",
      "TailwindCSS",
      "NodeJS",
      "Vite",
      "Flask",
      "OpenAI",
      "Firebase",
    ],
  },
  {
    name: "Agham Tales",
    description: "n/a",
    image: "/assets/projects/agham_tales_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Flutter", "Dart", "Firebase"],
  },
  {
    name: "Angels Burger Inventory System",
    description:
      "Commisioned by a student from Surigao State University, It is an automatic inventory system where staff can inventorize their products and materials. It has also an administrator access where managers can see their staffs' records. With this app there is a transparency that minimizes corruption and it helps the stores to be on track with the number of its material and products.",
    image: "/assets/projects/angels_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Baligyaay",
    description: "n/a",
    image: "/assets/projects/baligyaay_web.png",
    link: "",
    date: "n/a",
    type: "web",
    technologies: ["C#", "ASP.NET", "SQL Server", "Bootstrap", "JQuery"],
  },
  {
    name: "Bantay Alta Presyon",
    description: "n/a",
    image: "/assets/projects/bantayalta_web.png",
    link: "",
    date: "n/a",
    type: "web",
    technologies: [
      "React",
      "Typescript",
      "InertiaJS",
      "Laravel",
      "TailwindCSS",
      "PostgreSQL",
      "Sanctum",
      "ShadCN",
    ],
  },
  {
    name: "Beart",
    description:
      "Beart is an app that allows artist known by uploading it online and earning money through sales or commission pay.",
    image: "/assets/projects/beart_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Budyet ta Bai",
    description:
      "Budyet Ta Bai is your ultimate cash-monitoring mobile tool. With Budyet Ta Bai, you can effortlessly keep track of your finances on the go. Our powerful app is designed to give you complete control over your money",
    image: "/assets/projects/budyet_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Cake Onlineshop",
    description:
      "Concept mobile application for contactless doing of order and has an inventory system feature. It is a Digital-Menu where customers can select their desired order and get the total expenses in an instant. It supports in-store purchase and door-to-door delivery purchase.",
    image: "/assets/projects/cake_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Chat Desktop App",
    description:
      "Chat App is a Java Swing-based messaging application that stands out for its passwordless login and end-to-end encryption. Users can have secure one-on-one conversations without needing a traditional username and password. The app keeps messages private and offers a straightforward, user-friendly interface for hassle-free, confidential communication.",
    image: "/assets/projects/chat_desktop.png",
    link: "",
    date: "n/a",
    type: "desktop",
    technologies: ["Java Swing", "Firebase"],
  },
  {
    name: "Cinnamontifier",
    description: "n/a",
    image: "/assets/projects/cinnamontifier_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: [
      "Flutter",
      "Dart",
      "Flask",
      "Matplotlib",
      "Pandas",
      "Firebase",
    ],
  },
  {
    name: "Crispy King Order System",
    description:
      "Concept mobile application for contactless doing of order and has an inventory system feature. It is a Digital-Menu where customers can select their desired order and get the total expenses in an instant. It supports in-store purchase and door-to-door delivery purchase.",
    image: "/assets/projects/crispy_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "DATM Console",
    description:
      "dATM Bank System is a user-friendly banking system with various features. Authenticated users can perform tasks like checking their account balance, withdrawing and depositing cash, viewing account details, transaction history, changing account number and PIN, transferring money, and signing out.",
    image: "/assets/projects/datm_console.png",
    link: "",
    date: "n/a",
    type: "desktop",
    technologies: ["C"],
  },
  {
    name: "Dcalculator",
    description:
      "The Simple Calculator with Clean UI is a user-friendly app that provides basic arithmetic functionality in a minimalist and intuitive interface. Designed for simplicity and ease of use, this calculator allows users to perform simple calculations quickly and efficiently.",
    image: "/assets/projects/dcalculator_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML"],
  },
  {
    name: "Dconverter",
    description:
      "The All-in-One Converter app in Java is a comprehensive tool that simplifies conversions in math, geometry, and measurements. It offers users a convenient way to convert values between different units and systems, making calculations and conversions hassle-free.",
    image: "/assets/projects/dconverter_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML"],
  },
  {
    name: "Dextrolio V2",
    description: "n/a",
    image: "/assets/projects/dextrolio_v2_web.png",
    link: "",
    date: "n/a",
    type: "web",
    technologies: ["ReactJS", "TailwindCSS", "NodeJS", "Vite"],
  },
  {
    name: "Dextrolio V3",
    description: "n/a",
    image: "/assets/projects/dextrolio_v3_web.png",
    link: "",
    date: "n/a",
    type: "web",
    technologies: ["NextJS", "TailwindCSS", "NodeJS", "Typescript"],
  },
  {
    name: "Digipa",
    description:
      "DIGIPA is more than just an app; it's your academic partner. With its cutting-edge automatic PDF scanner, you can now effortlessly scan your PDF grades and watch as your GPA is computed accurately in a matter of seconds. No more manual calculations, no more stress – just one click, and your GPA is at your fingertips.",
    image: "/assets/projects/digipa_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase", "Flask", "Tabula"],
  },
  {
    name: "DKeylogger",
    description:
      "It is a powerful software application that discreetly records and captures keystrokes entered on a computer system. This specialized keylogger not only logs the keystrokes but also incorporates an SMTP (Simple Mail Transfer Protocol)functionality.",
    image: "/assets/projects/dkeylog_desktop.png",
    link: "",
    date: "n/a",
    type: "desktop",
    technologies: ["C#", "Winforms"],
  },
  {
    name: "DMusic",
    description:
      "Java Firebase Console Music Player is a feature-rich app that offers users a seamless music streaming and downloading experience. Developed in Java, the app integrates with Firebase, a popular cloud-based platform, to provide a robust backend infrastructure.",
    image: "/assets/projects/dmusic_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML"],
  },
  {
    name: "DYutube",
    description: "n/a",
    image: "/assets/projects/dyoutube_desktop.png",
    link: "",
    date: "YouTube downloader written in C# with an API is a powerful tool that allows users to download videos from YouTube directly to their devices. It leverages the capabilities of the YouTube API to fetch video metadata and download the corresponding video files.",
    type: "desktop",
    technologies: ["C#", "Winforms"],
  },
  {
    name: "DYT",
    description:
      "DYT is a versatile application designed for converting YouTube links to both MP3 audio and MP4 video formats. In addition to its conversion capabilities, the app provides a user-friendly interface that allows you to browse, search for specific videos, and conveniently select content for download in just one click. This makes it a handy tool for users looking to easily extract audio or video content from YouTube for offline use.",
    image: "/assets/projects/dyt_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML"],
  },
  {
    name: "EMenu",
    description:
      "Concept mobile application for contactless doing of order and has an inventory system feature. It is a Digital-Menu where customers can select their desired order and get the total expenses in an instant. It supports in-store purchase and door-to-door delivery purchase.",
    image: "/assets/projects/emenu_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Grading Systen",
    description:
      "It is a concept of Automatic Information Management System a.k.a AIMS, It is a platform where professors or the management can add students, do announcements and can post the ratings/grades of students enrolled in their institution.",
    image: "/assets/projects/grading_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "ICT Modules",
    description:
      "ICT Modules is the app that stores many documents and lessons about ICT strand which free to browse to all users in order to learn. There is a quiz also to test your knowledge.",
    image: "/assets/projects/ict_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Kemitoon",
    description:
      "KemiToon is a dynamic Android-based application, meticulously curated to bring the world of Chemistry to life through captivating comics. Designed with a clear educational focus, this app offers a unique approach to understanding high school-level Chemistry concepts.",
    image: "/assets/projects/kemitoon_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Flutter", "Dart", "Firebase"],
  },
  {
    name: "KT Movers",
    description: "n/a",
    image: "/assets/projects/ktmovers_web.png",
    link: "",
    date: "n/a",
    type: "web",
    technologies: [
      "ReactJS",
      "Typescript",
      "NodeJS",
      "Vite",
      "Firebase",
      "Mapbox",
      "TailwindCSS",
    ],
  },
  {
    name: "MLBB Winrate Calculator",
    description: "n/a",
    image: "/assets/projects/mlbb_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML"],
  },
  {
    name: "Moving Market",
    description: "n/a",
    image: "/assets/projects/moving_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "OBO Mandaue",
    description:
      "A java swing app that serves as storage for the important files such as Occupancy files and Building Permit of the city",
    image: "/assets/projects/obo_desktop.png",
    link: "",
    date: "n/a",
    type: "desktop",
    technologies: ["Java Swing", "Firebase"],
  },
  {
    name: "Pesoearn",
    description:
      "Pesoearn is a mobile application that offers users the opportunity to earn rewards while enjoying various audio content such as podcasts, audiobooks, and more. By listening to these audio materials, users can accumulate credits based on the value set by advertisers and sponsors.",
    image: "/assets/projects/pesoearn_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Prohealth",
    description: "n/a",
    image: "/assets/projects/prohealth_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Tensorflow Lite"],
  },
  {
    name: "Projbyte",
    description:
      "Projbyte is an innovative and dynamic mobile application that serves as a thriving hub for developers and technology students. This powerful platform fosters a vibrant community where users can explore a diverse range of engaging content such as blogs, tutorials, and forums.",
    image: "/assets/projects/projbyte_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Roadgrill Order System",
    description:
      "Concept mobile application for contactless doing of order and has an inventory system feature. It is a Digital-Menu where customers can select their desired order and get the total expenses in an instant. It supports in-store purchase and door-to-door delivery purchase.",
    image: "/assets/projects/roadgrill_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "School Roll Attendance",
    description:
      "A simple attendance system that get the information on what date and time the user in and out. It also supported camera feature when logging",
    image: "/assets/projects/school_roll_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Scimet",
    description: "n/a",
    image: "/assets/projects/scimet_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Flutter", "Dart", "Firebase"],
  },
  {
    name: "Student Management",
    description: "n/a",
    image: "/assets/projects/student_crud_web.png",
    link: "",
    date: "n/a",
    type: "web",
    technologies: ["Python", "DJango", "SQLite", "TailwindCSS"],
  },
  {
    name: "Tindakart",
    description: "n/a",
    image: "/assets/projects/tindakart_desktop.png",
    link: "",
    date: "n/a",
    type: "desktop",
    technologies: ["Java Swing", "PostgreSQL"],
  },
  {
    name: "SSCT Voting System",
    description:
      "Commissioned by a Student from Surigao State University, Its main function is an automated voting system where admistrators can add candidates and their respective positions. After the voting process the mobile application hosted in FireBase will automatically compute the tally of votes gathered during the contactless election.",
    image: "/assets/projects/voting_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Zlec",
    description:
      "It is a social media platform that give user information, tutorials and awareness about cybersecurity. This app contains categories that represents hacking methods and there's a feed that can post their concerns.",
    image: "/assets/projects/zlec_mobile.png",
    link: "",
    date: "n/a",
    type: "mobile",
    technologies: ["Java", "XML", "Firebase"],
  },
  {
    name: "Prezstige",
    description:
      "Prezstige is a loyalty management platform that helps MSMEs in the Philippines skyrocket their sales through effective loyalty programs. Prezstige offers digital and physical loyalty cards — including paper, QR, and NFC-powered options — tailored for our partner merchants.",
    image: "/assets/projects/prezstige_web.png",
    link: "https://prezstige.com/",
    date: "n/a",
    type: "mobile",
    technologies: ["Next.js", "React Native", "Expo", "Supabase", "Typescript", "Shadcn", "TailwindCSS"],
  },
  {
    name: "BarangMI",
    description:
      "BarangMI for the future. Streamline barangay operations with AI, multi-tenancy, configurable features, and a centralized platform to manage your community.",
    image: "/assets/projects/barangmi_web.png",
    link: "https://barangmi.com/",
    date: "n/a",
    type: "web",
    technologies: ["React", "TailwindCSS", "PostgreSQL", "Typescript", "Shadcn", "Laravel", "JWT", "Spatie", "PHP", "React Native", "Expo", "Python", "Flask", "NX Monorepo", "Vite", "Node JS", "SMTP"],
  },
];
