export const techStack = [
  {
    category: "Frontend",
    techs: [
      "React",
      "TypeScript",
      "Next.js",
      "Tailwind CSS",
      "Vite",
      "Prettier",
    ],
  },
  {
    category: "Backend",
    techs: [
      "Laravel",
      "PHP",
      "Node.js",
      "JWT",
      "Python",
      "ASP.NET",
      "REST API",
      "Slim",
      "Django",
      "Flask",
    ],
  },
  {
    category: "Database",
    techs: ["PostgreSQL", "Firebase"],
  },
  {
    category: "Mobile",
    techs: ["React Native", "Flutter", "Android"],
  },
  {
    category: "Desktop",
    techs: ["Java Swing", ".NET", "VB.NET"],
  },
  {
    category: "AI & Machine Learning",
    techs: [
      "Tensorflow",
      "OpenAI",
      "Gemini",
      "PyTorch",
      "Keras",
      "Scikit-learn",
      "Yolo",
      "Pandas",
    ],
  },
  {
    category: "Developer Tools",
    techs: [
      "Github",
      "VS Code",
      "Git",
      "JetBrains IntelliJ IDEA",
      "PyCharm",
      "Cursor",
      "Postman",
      "Swagger",
      "Discord",
      "Teams",
      "Trello",
      "Notion",
      "Figma",
      "Canva",
      "Microsoft Office",
    ],
  },
];
